ARG VERSION=latest
FROM python:$VERSION

RUN apt-get update \
    && apt-get install -y default-jdk ant

WORKDIR /usr/lib/jvm/default-java/jre/lib
RUN ln -s ../../lib amd64

WORKDIR /usr/src/pylucene
RUN curl https://downloads.apache.org/lucene/pylucene/pylucene-8.3.0-src.tar.gz \
    | tar -xz --strip-components=1
RUN cd jcc \
    && NO_SHARED=1 JCC_JDK=/usr/lib/jvm/default-java python setup.py install
RUN make all install JCC='python -m jcc' ANT=ant PYTHON=python NUM_FILES=10

WORKDIR /usr/src
RUN rm -rf pylucene

RUN wget https://github.com/Silleellie/orange_cb_recsys/raw/master/setup.py && wget https://github.com/Silleellie/orange_cb_recsys/raw/master/requirements.txt && wget https://github.com/Silleellie/orange_cb_recsys/raw/master/README.md
RUN python setup.py install
RUN python -m pip install PyYaml
