ARG VERSION=3.8
FROM python:$VERSION

RUN wget https://github.com/Silleellie/orange_cb_recsys/raw/master/setup.py \
    && wget https://github.com/Silleellie/orange_cb_recsys/raw/master/requirements.txt \
	&& wget https://github.com/Silleellie/orange_cb_recsys/raw/master/README.md
RUN pwd
