---
- content_type: "ITEM"
  output_directory: "../../contents/movielens_test_exo_prop"
  raw_source_path: "../../datasets/movies_info_reduced.json"
  source_type: "json"
  id_field_name:
  - "imdbID"
  get_exogenous_properties:
    - class: 'dbpedia_mapping'
      mode: 'only_retrieved_evaluated'
      entity_type: 'Film'
      lang: 'EN'
      label_field: 'Title'
  fields: []

- content_type: "RATING"
  output_directory: "file_path"
  raw_source_path: "file_path"
  source_type: "dot"
  from_field_name: "from"
  to_field_name: "to"
  timestamp_field_name: "timestamp"
  fields:
    - field_name: "recensione"
      processor:
        class: "text_blob_sentiment"
    - field_name: "stelle"
      processor:
        class: "number_normalizer"
        min: "1"
        max: "5"