name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Login to DockerHub
        uses: ./Dockerfile/Dockerfile
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
#     -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prova:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
