name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file:  Dockerfile/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prova:latest
      -
         name: Test
         working-directory: /
         run: | 
                ls
                docker images
                container_id=$(docker run -d -it -v $(pwd):/usr/src ${{ secrets.DOCKER_USERNAME }}/prova)
                docker exec -it $container_id pip install coverage coveralls
                docker stop $container_id
                docker container rm $container_id
