name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  main:
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: "prova"

    steps:
      - 
       name: Checkout 
       uses: actions/checkout@v2
       with:
          fetch-depth: 0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Setup python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8 #install the python needed
      -
        name: Check File Changed
        id: check
        run: |
              git diff --name-only HEAD^ HEAD > files.txt
              echo "::set-output name=must_build::false"
              while IFS= read -r file
              do
                if [[ $file == */Dockerfile ]] || [[ $file == setup.py ]]; then
                  echo "::set-output name=must_build::true"
                  echo "Necessario buildare immagine Docker"
                  break
                fi
              done < files.txt
              rm files.txt
              if ${{ steps.check.outputs.must_build == 'false' }}; then
                if ! docker pull ${{ secrets.DOCKER_USERNAME }}/${{ IMAGE_NAME }}:latest; then
                    echo "::set-output name=must_build::true"
                    echo "Necessario buildare immagine Docker"
                fi
              fi
              
      -
        name: Set up Docker Buildx
        if: ${{ steps.check.outputs.must_build == 'true' }}
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        if: ${{ steps.check.outputs.must_build == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.WORKSPACE }}
          file:  Dockerfile/Dockerfile
          load: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prova:latest
#   test:
#     container:
#       image: silleellie/prova
#       options: -t -v ${pwd}:/usr/src
    
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#               ls
#               echo "wee"
#               pip install coverage coveralls pytest
#               python -m pytest test/content_analyzer/test_run.py
      -
         name: Test
         run:
               |
                container_id=$(docker run -d -v "$(pwd)":/usr/src -it  ${{ secrets.DOCKER_USERNAME }}/prova)
                docker exec -i $container_id pip install coverage coveralls pytest
                docker exec -i $container_id coverage run --source=orange_cb_recsys -m unittest
                docker stop $container_id
                docker container rm $container_id
      -
         name: Push image to Docker
         id: docker_push
         if: ${{ steps.check.outputs.must_build == 'true' }}
         run: docker push ${{ secrets.DOCKER_USERNAME }}/prova
      
